NUMPY ARRAY OLUŞTURMA

# NUMPY

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4])

In [3]:
type(x) 

numpy.ndarray

# NUMPY İNDEKSLEME

# Tek Boyutlu Dizi

In [16]:
n=np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
n[3]

3

In [18]:
n[3:6]

array([3, 4, 5])

In [19]:
n[4]=1000
n

array([   0,    1,    2,    3, 1000,    5,    6,    7,    8,    9])

In [21]:
for i in n:
    print(i*2)

0
2
4
6
2000
10
12
14
16
18


In [22]:
n=np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
n=np.arange(10,50,5)
n

array([10, 15, 20, 25, 30, 35, 40, 45])

In [24]:
ondalik=np.arange(0,2,0.2)
ondalik

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [26]:
lin = np.linspace(0,4,12) #0 ile 4 arasında 12 adet sayı üretiyor.
lin

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

# Çok Boyutlu Dizi

In [27]:
rast=np.random.rand(3,4) #3 satır 4 sütun bir matris
rast

array([[0.49689592, 0.47574031, 0.38711423, 0.15975189],
       [0.45974849, 0.29975774, 0.84472925, 0.29290065],
       [0.56798652, 0.23195273, 0.25693155, 0.95256088]])

In [29]:
n=np.random.randn(2,5) #Normal dağıılımda oluşturur. -/+ 0-1
n

array([[ 0.8099978 ,  1.93760237,  0.53491532, -2.55789809,  1.70547758],
       [-0.52561536, -0.50366701,  0.29717324,  1.38874223,  0.11394665]])

In [30]:
np.random.randint(1,50,15)

array([ 7, 42, 42, 48, 38, 40, 30, 29, 38,  9, 33,  7, 36, 16, 41])

In [31]:
#Dizinin Boyutu
numpy_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array1.ndim)

1


In [33]:
numpy_array2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(numpy_array2.ndim)

2


In [34]:
#Dizinin satır ve sütun sayısı
numpy_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array1.shape)
print(numpy_array1.ndim)

(10,)
1


In [35]:
numpy_array2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(numpy_array2.ndim)
print(numpy_array2.shape)

2
(1, 10)


In [36]:
y=np.arange(24)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
#Dizinin satır sütun sayısını değiştirme
y.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
y.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
y.ravel() #Tek boyutlu haline getirme

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
y=np.random.random(16)
y

array([0.739915  , 0.51860758, 0.43651093, 0.90484913, 0.24775193,
       0.04876367, 0.43214626, 0.18902966, 0.93842895, 0.50152438,
       0.20891847, 0.35340019, 0.18706743, 0.76716213, 0.66288781,
       0.30914603])

In [45]:
y=y.reshape(4,4)
y

array([[0.739915  , 0.51860758, 0.43651093, 0.90484913],
       [0.24775193, 0.04876367, 0.43214626, 0.18902966],
       [0.93842895, 0.50152438, 0.20891847, 0.35340019],
       [0.18706743, 0.76716213, 0.66288781, 0.30914603]])

In [46]:
y.ravel() 

array([0.739915  , 0.51860758, 0.43651093, 0.90484913, 0.24775193,
       0.04876367, 0.43214626, 0.18902966, 0.93842895, 0.50152438,
       0.20891847, 0.35340019, 0.18706743, 0.76716213, 0.66288781,
       0.30914603])

In [47]:
y[0:2,1]

array([0.51860758, 0.04876367])

In [48]:
y[:3]

array([[0.739915  , 0.51860758, 0.43651093, 0.90484913],
       [0.24775193, 0.04876367, 0.43214626, 0.18902966],
       [0.93842895, 0.50152438, 0.20891847, 0.35340019]])

In [49]:
for satir in y:
    print(satir)

[0.739915   0.51860758 0.43651093 0.90484913]
[0.24775193 0.04876367 0.43214626 0.18902966]
[0.93842895 0.50152438 0.20891847 0.35340019]
[0.18706743 0.76716213 0.66288781 0.30914603]


In [51]:
for satir in y.flat:
    print(satir)

0.7399150016044189
0.5186075760210521
0.43651093055774115
0.9048491290620627
0.24775192807278368
0.04876366621637174
0.43214626122845046
0.18902965661119386
0.9384289473444384
0.5015243800368897
0.20891847107931893
0.3534001944999704
0.18706743098879097
0.7671621277467643
0.6628878126170343
0.3091460306450098


In [52]:
#satır ve sütun gösterme
for satir in np.ndenumerate(y):
    print(satir)

((0, 0), 0.7399150016044189)
((0, 1), 0.5186075760210521)
((0, 2), 0.43651093055774115)
((0, 3), 0.9048491290620627)
((1, 0), 0.24775192807278368)
((1, 1), 0.04876366621637174)
((1, 2), 0.43214626122845046)
((1, 3), 0.18902965661119386)
((2, 0), 0.9384289473444384)
((2, 1), 0.5015243800368897)
((2, 2), 0.20891847107931893)
((2, 3), 0.3534001944999704)
((3, 0), 0.18706743098879097)
((3, 1), 0.7671621277467643)
((3, 2), 0.6628878126170343)
((3, 3), 0.3091460306450098)


In [53]:
c=np.random.randint(1,50,15)
c

array([17, 45, 30, 10, 22, 29,  2, 38, 32,  5, 29, 24, 23, 18, 17])

In [54]:
c.max()

45

In [55]:
c.min()

2

In [56]:
c.argmax() #max değerinin indexi

1

In [57]:
c.argmin()

6

In [78]:
a=np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [79]:
a.shape = 2,:,5 #??
a.shape

SyntaxError: invalid syntax (<ipython-input-79-9fcc8de96378>, line 1)

In [80]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [81]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
np.ones((2,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [84]:
#np.eye() → Belirlenen boyutlarda birim matris oluşturmamızı sağlayan fonksiyon
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
a=np.array([2,3])
b=np.array([5,6])

In [86]:
np.hstack((a,b)) #Yatay Birleştirme

array([2, 3, 5, 6])

In [87]:
np.vstack((a,b)) #Dikey Birleştirme

array([[2, 3],
       [5, 6]])

In [88]:
#Dizinin elemanlarını seçmek
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [89]:
#Dizinin herhangi bir satırını seçmek
#1.satır
first_row = numpy_array[0]
print(first_row)

[0 1]


In [90]:
#1. ve 2. satır 
first_and_second_rows = numpy_array[0:2]
print(first_and_second_rows)

[[0 1]
 [2 3]]


In [91]:
#Dizinin herhangi bir kolonunu seçmek
#1. sütun
first_column = numpy_array[:,0]
#1. ve 2. sütun
first_and_second_column = numpy_array[:,0:2]
print(first_column)
print(first_and_second_column)

[0 2 4 6 8]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [92]:
#Dizinin herhangi bir elemanını seçmek
selecting_item = numpy_array[3,1]
print(selecting_item)

7


In [93]:
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [94]:
print(numpy_array[::-1])

[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]


In [96]:
#Matris Birleştirme
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
numpy_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [97]:
#Satır bazlı birleştirme
print(np.concatenate((numpy_array, numpy_array), axis =0))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [98]:
#Sütun bazlı birleştirme
print(np.concatenate([numpy_array, numpy_array], axis =1))

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]
 [8 9 8 9]]


In [100]:
#Matrisin satırlarını sütun, sütunlarını satır yapma işlemi numpy ile “ .T” yazmak kadar kolay.
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [101]:
#3Boyutlu Dizileri Yineleme
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [102]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8


In [103]:
#Nditer() Kullanarak Dizileri Yineleme
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# NUMPY İŞLEMLER

In [104]:
import numpy as np

In [108]:
a = np.array([20,40,60,80])
a

array([20, 40, 60, 80])

In [111]:
b=np.arange(4)
b

array([0, 1, 2, 3])

In [112]:
c=a+b
c

array([20, 41, 62, 83])

In [113]:
a**2

array([ 400, 1600, 3600, 6400])

In [114]:
a>50

array([False, False,  True,  True])

In [115]:
a+=10
a

array([30, 50, 70, 90])

In [116]:
x=np.random.random(12)
x

array([0.24593861, 0.81181529, 0.22227499, 0.7345476 , 0.00166145,
       0.28320389, 0.42393514, 0.09875496, 0.83271819, 0.95127891,
       0.85059972, 0.00181818])

In [117]:
x.max()

0.9512789088704453

In [118]:
x.min()

0.0016614495723897837

In [119]:
x.sum()

5.458546949109634

In [120]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
b.sum(axis=0) #Sütun değerler toplamı

array([15, 18, 21, 24, 27])

In [123]:
b.sum(axis=1) #Satır değerler toplamı

array([10, 35, 60])

In [124]:
b.max(axis=1) #Satırlardaki en büyük değerler

array([ 4,  9, 14])

In [125]:
b.cumsum(axis=1) #Satırlardaki değerler kendisinden önceki sayıları toplarak ilerler

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [126]:
k=np.random.random(10)
k

array([0.22091434, 0.89547185, 0.35874133, 0.3870394 , 0.39607556,
       0.93802643, 0.5214504 , 0.8337562 , 0.3909514 , 0.26076662])

In [127]:
k.mean() #Ortalama

0.520319352930491

In [128]:
np.median(k) #median alma (ortanca değer)

0.39351347944791054

In [129]:
np.std(k) #Standart sapma

0.25426700843694783

In [130]:
np.var(k) #Varyasyon

0.0646517115794749

In [131]:
kopya=k.copy()
kopya

k[0] = 42

print(k) 
print(kopya) 

[42.          0.89547185  0.35874133  0.3870394   0.39607556  0.93802643
  0.5214504   0.8337562   0.3909514   0.26076662]
[0.22091434 0.89547185 0.35874133 0.3870394  0.39607556 0.93802643
 0.5214504  0.8337562  0.3909514  0.26076662]


In [133]:
#Bir görünüm oluşturalım, orijinal diziyi değiştirelim ve her iki diziyi de görüntüleyelim
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
print(arr)
print(x)

arr[0] = 42

print(arr) 
print(x)  

[1 2 3 4 5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [134]:
citys=np.array(["ankara","istanbul","bursa","ankara",'izmir',"bursa",'izmir'])
np.unique(citys)

array(['ankara', 'bursa', 'istanbul', 'izmir'], dtype='<U8')

# Matrislerde aritmetik işlemler

In [135]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(3,3)
#dizimizi 3x3 lük, 2 boyutlu bir matrise dönüştürdük.
print(numpy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [136]:
print(numpy_array + numpy_array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [137]:
print(numpy_array - numpy_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [138]:
print(numpy_array * numpy_array)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [139]:
print(numpy_array / numpy_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [140]:
print(numpy_array + 5)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [141]:
print(numpy_array * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Özel foksiyonlar ile işlemler

In [142]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(3,3)
#dizimizi 3x3 lük, 2 boyutlu bir matrise dönüştürdük.

In [143]:
print(np.sin(numpy_array))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [144]:
print(np.cos(numpy_array))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [145]:
print(np.sqrt(numpy_array))  

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [146]:
print(np.exp(numpy_array))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [147]:
print(np.log(numpy_array))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [149]:
#Matrislerin çarpımı
#Bu bölüme ,iki matris çarpılırken ilk matrisin sütun sayısının ikinci matrisin satır sayısına eşit olması gerektiğini hatırlayarak başlayalım.
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array1 = numpy_array.reshape(5,2)
print(numpy_array1)
numpy_array2 = numpy_array.reshape(2,5)
print(numpy_array2)
print(np.dot(numpy_array1,numpy_array2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [150]:
#Matrisin transpozu
#Matrisin satırlarını sütun, sütunlarını satır yapma işlemi numpy ile “ .T” yazmak kadar kolay.
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [151]:
print(numpy_array.T) 

[[0 2 4 6 8]
 [1 3 5 7 9]]


# Numpy’da Koşul İfadeleri ile Çalışmak

In [152]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
boolean_array = numpy_array >= 5
print(boolean_array)

[False False False False False  True  True  True  True  True]


In [153]:
# 5 ve 5'ten büyük elemanlar
print(numpy_array[boolean_array])

[5 6 7 8 9]


In [154]:
# 5 ten küçük elemanlar
print(numpy_array<5)
print(numpy_array[numpy_array<5])

[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


# NUMPY EXERCISES